:code: ..

= From Beans to Boot

You know, I am assuming that by the time you're reading this that you have some background with Spring. I assumed the same thing about one of earlier books, _Reactive Spring_, too, but I included a _very_ simple discussion of some of the core principles of Spring in that book and - to my utter shock and chagrin - it was one of the most loved aspects of the book! I couldn't believe it!

So, here we go. We're going to do the same sort of thing, but of course greatly udpated to reflect the amazing moemnt in which we fnd ourselves.

when spring first came out we talked about the "spring triangle"  the three pillars that made the Spring Framework so useful for people:
 * portable service abstractions
 * dependency injection
 * autoconfiguration

more recently, with the introduction mof Spring Boot, we've added a new dimension of utility to the framework: autoconfiguration. So I guess its more like a "Spring square" now, come to think of it.

At the core of Spring as a framework is the fact htat it needs to understand how your objects are wired together. But why? why bother telling it these things? Why not just wire things yourself?

at the microlevel, this isnt an unreasonable quesiton. spring is just java and i can write java without spring, so why bother with Spring?

let's introduce a _trivial_ example to enforce the idea. Were going to read `Dog` data from a SQL database, PostgreSQl, running on our machine. Well use the follwoing Docker Compose file to stand up the instance of our database.

----
include::{code}/beans-to-boot/beans-to-boot/compose.yml[]
----
.run this in the usual way: `docker compose up -d`

// raw start
* spring 'square' : psb, aop, di, autoconfig
* basic repository
* core java
* DataSource inline
// raw stop

// di start
* use DI to extract it out; nothing fancy just polymorphism.
// di start
// psb start
* use JdbcClient
// psb start
// psb tx1
* what about tx?
* oop says dry; extract single responsibility to another class
* TransactionalDogRepository is a composite that wraps the target one
* platformtxmanager
// psb tx1
* transactiontemplate
* still very tedious tho is there some way to programatically generate new implementations of the interface?
* jdk proxies
* now we can wrap our target with our new `transactional` method
* its nie but things are getting out of hand. that said, our code is approachable enough for now. bear in mind were (barely) doing any persistence
* lets see if spring can improve things
* turn everything into beans
* there is a lifecycle at play. i can control the beans construction and destuction. they can implement InitializingBean && DisposablBean
* these callbacks are nbut one way to participate in important lifecycle events. another is to use `ApplicationEvent`s. there are a ton of them! lets implement a simple `@EventListener`
* the lifecycle is interesting. when the app starts up and shuts down ur code can hook into the lifecycle.
* > ingest -> BeanDefintiions -> beans
* BeanFactoryPostProcessor lets u see the BeanDefintions
* what we want is BeanPostProcessor
* extract the transactional support to this based on presence of marker interface `Tx`
* obviously, if u have used spring at all before then u prolly know where this is going: we've already done this exact magic trick. let's refactor to use `@transactional`. just need to enable it with `@EnableTransactionManagment`
* nice but of course its tedious to define beans with full config every time. lets use implicit configuration and `@ComponentScan`
* component scanning for our repository by adding `@Repository`
* stereotype annotations are neat. u can create ur own, too
* this is _implicit_ configuration
* as opposed to the explicit configuration
* Spring Framework 7 introduced `BeanRegistrar`s, too, btw. here's how that would look.
* anyway weve done a lot here. but weve got harccoded configuration. let's extricate the values to properties (`application.properties`) and use the `Environment`
* it's nice! but theres a lot of boilerplate thatll prolly be the same from one appt o another.
* lets use Spring Boot. same `ApplicationContext` but the code is much simpler. We can delete everything except the DogRepository and the `test` method
* this works because of AutoConfiguration. you can create your own too. the autoconfig is activated by the presence of `starters`.
* and, being honest, im not sure we ever needed to implement the repository ourselves. lol. lets just use the Sprig Dats JDBC project.
* note that weve also now got good ascii art. we've got an actuator. weve got a web server.
* we can use virutal threads!
* remember the BEanDfinitions? we can turn this into a graalvm native image!
* use spring boot's build plugin to create a docker image, too