:code: ..

= From Beans to Boot

I am assuming that by the time you're reading this that you have some understanding of Spring.
I assumed the same thing about one of earlier books, _Reactive Spring_, too, but I included a _very_ simple discussion of some of the core principles of Spring in that book and - to my utter shock and chagrin - it was one of the most loved aspects of the book!
I couldn't believe it!

So, here we go.
We're going to do the same sort of thing, but of course greatly udpated to reflect the amazing moemnt in which we fnd ourselves.

when spring first came out we talked about the "spring triangle" the three pillars that made the Spring Framework so useful for people:

* portable service abstractions
* dependency injection
* autoconfiguration

more recently, with the introduction mof Spring Boot, we've added a new dimension of utility to the framework: autoconfiguration.
So I guess its more like a "Spring square" now, come to think of it.

At the core of Spring as a framework is the fact htat it needs to understand how your objects are wired together.
But why? why bother telling it these things?
Why not just wire things yourself?

at the microlevel, this isnt an unreasonable quesiton. spring is just java and i can write java without spring, so why bother with Spring? lets learn what spring can help you with by way of an example that well start from scratch, iteratively letting Spring do more and more to reduce code and elevate results.

but first, we'll need a database...

== a supporting database

let's introduce a _trivial_ example to enforce the idea.
Were going to read `Dog` data from a SQL database, PostgreSQl, running on our machine.
Well use the follwoing Docker Compose file to stand up the instance of our database.

----
include::{code}/beans-to-boot/beans-to-boot/compose.yml[]
----

.run this in the usual way: `docker compose up -d`

// db start
* theres some SQL for schema and data in `schema.sql` and `data.sql`. run `docker compose up -d` then make sure to pass that SQL to postgresql:

```shell
cat src/main/resources/schema.sql | PGPASSWORD=secret psql -Umyuser -hlocalhost mydatabase
cat src/main/resources/data.sql | PGPASSWORD=secret psql -Umyuser -hlocalhost mydatabase
```

// db stop

// raw start
== a repository of knowledge.. about dogs

we're going to be working with data about dogs. so well need a layer to read that data and make it available to us. here's a strawman first cut at this code, with several less-than-ideal design decisions. lets look at the moving parts. well introduce all of them now and only the things that change as we progress.

first, the holder for data coming from our `dog` table.

-----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/raw/Dog.java[]
-----

. a java record is a marvelous thing

well be implementing a repository. here's the interface for that repository.

-----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/raw/DogRepository.java[]
-----

.it seems simple enough..
and here's the default implementation of that interface.

-----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/raw/DefaultDogRepository.java[]
-----

. everything about this arangement makes me itch: `DataSource` objects are expensive and should be pooled and centralized and reused for mayn objects.
I dont love credentials harcocded into the source code. and i dont love that were instantiating the expensive resource in the constructor instead of centralizing its ddefinition and having it passed in via injection.
. believe it or not, this demo used to be a _lot_ worse when i first started teaching Spring to folks (even if just others on my team) 20+ years ago. the ability to use Java 7's `Autocloseable` is a game-changer for this sort of code.
Just hope you remember to use it!
You definitely dont want these things leaking.

and of course heres the entry point into this example. all `Main` classes will have the same basic formula: use an instance of `DogRepository` to read data and iterate over the data.

-----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/raw/Main.java[]
-----

. first we create an instance..
. ..then we pass it to a `test` method which expects an instance of an interface and doesn' care about how we got it


// raw stop
// di start
== Dependency Injection

You probably alreadys aw this coming.
We should centralize that `DataSource` definition. here's the updated `Main` and `DefaultDogRepository`.

-----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/di/Main.java[]
-----

and here's the `DogRepository` implementation. there shouldn't be much to say.
This is, after all, just using constructors in an object-oriented language. but i'll say a few things anyway, because there was a time when that kind of code used to be fairly common.

when i first started using java id see a lot of code written like the first example, with the datasource initialized _inside_ the thing that used it. this was because a lot of programmers who first adopted Java when i started using it came from C++ and C backgrounds. in those paradigms, developers were forced to manage memory, and if any of the memory got away from the programmer, you'd get an insidious memory leak!
So we had a pattern: RAII.
Resource Acquisition Is Initialization. the idea was that we bound things that needed to be managed-memory, sockets, etc. - to the lifecycle of the smallest scope, usually that of the object that used it.
Put another way, if a Foo needed a Bar, itd create it in the Foo constructor and it'd destory it in the `Foo` _destructor_, a concept we dont really have in Java.
Because java has a garbage collector. its fine if objects have lifetimes longer than the things that use them.

DataSources tend to be expensive, especially once you have connection pooling.
Youll want ot keep tabs on where the DataSource is built, its pool size, etc. several benefits here.

one its easier to maintain as you only need to change things in one place. two were writing our code

Anyway here's the updated repository with the constructor.
One of the benefits of the constructor is that its written against the lowest common type, `javax.sql.DataSource`. were using Spring's built-in (and _not_ production-worthy) `DriverManagerDataSource`.
It does _not_ do connection pooling or anything interesting.
It just implements the `DataSource`.
In a production envirnment youd likely replac it with a more appropriately configured HikariCP connection pool.
In a test environment, you'd replace it with a mock.
Either way, you only need to change one thing in one place and pass it into constructors as you go.

-----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/di/DefaultDogRepository.java[]
-----

nothing fancy. just object-oriented programming, constructors, and leveraging the power of polymorphism. our constructors ecpect a `DataSource`, and we can give them any implementation we want without violating the contract.
// di start

// psb start
== Portable Service Abstractions

Looking at the code for the repository, it is a bit.. much.
I've written this sort of low-level `DataSource` manipulation code a million times in my career. trust me when i say that as terrible as it is, it could be _much worse_. thanks to the elegance of `Autocloseable`, most of the resource management code and the tedious wrapping of `try` / `catch` goes away.
But it's still a low-level approach to data access. this isnt even controversial.
JDBC is a driver, not an abstraction.
Its the lowest level of infrastructure for working with data in a SQL datbase. i bet if you asked, youd find most of the folks working on JDBC drivers ever expected people to use it directly. and good thing too, because it hurts.

Look at the code again. there are two things that are _essential_: the SQL query, and the mapping logic.
Everything else - creating the connection, prepared statements, result sets, iteration over the result sets, extracting out to lists, etc. it's boilerplate code that is far removed from whatever were trying to achieve in writing this code in the first place. (surely, there's _some_ business justification? right?)

let's rework this code to leverage one of Spring's many amazing _portable service abstractions_, the `JdbcClient`.

-----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/psb/DefaultDogRepository.java[]
-----

<.> look! there's the query we were talking about!
<.> and thgere's the mapper logic. clear as a bell!

i think we can agree, this is _much_ better.
// psb stop


== Unified Transaction Handling with `PlatformTransactionManager`
// tx1 start

this repository has just _one_ method and that method onyl executes _one_ read query. but what happens if that method has two queries?
What if they're both writes, modifying database state?

suppose were writing to the database and we want to add two records. the first record will go to a new `customers`s table that contains a list of all the people who have registered with our pet shop. the second will go to a table contaiing the customers expressed preferences for pets (small enough for condos or appartment-living, needs more aggressive routine grooming, etc.). these two records are related to each other. now imagine that, as soon as we write the first row, the power goes out and we dont manage to write the second row. now we have a record in an inconsistent state in the database. we cant help the customer until we sort out their preferences.
Or, imagine by some contrivance that the first write succeeds, then somebody comes along and deletes the customer before the second gets a chance to commit. now weve got preferences, but no customer!

the data is an inconsistewnt state. the normal way to handle this in a database system is to use transactions.
transactions are, broadly speaking, a way of batching and then either committing or rolling back work. it looks conceptually like this:

- start tx
** write 1
** write 2
** write 3
- if everything is good: commit _everything_ all at once
- else: rollback

This oversimplifies things a bit, but the main takeaway is that from the perspective of other SQL database cleints to the database, the system is never in-between states. it's all or nothing. they wont ever take action based on inconsistent or invalid database state.

It's a _truly_ powerful concept, and it has mirrors in all sorts of technologies. here's an abbreviated list:

- JMS
- JDBC
- JPA (based on JDBC)
- JDO (based on JDBC)
- JDB (based on JDBC)
- JOOQ (based on JDBC)
- Kafka
- AMQP (the protocol under RabbitMQ)
- Neo4J
- MongoDB
- Redis (to be fair: here transactions are more about batching than rollbacks)

and as yo might imagine, things can become disastrously complicated trying to work with transactions in a consistent way across all these technologies.
Some might reach to JTA, but this sort of reminds me of that old XKCD cartoon where in introducing the new standard, we've only introduced yet another imcompatible vairant of the thing being standardized.
It doesn't help.
Here, Spring has yet another very powerful portable service abstraction called `PlatformTransactionManager`.

NOTE: There's also a reactive variant too, but let's stick to bocking semantics for this example.

Here's the basic shape of Spring's `PlatformTransactionManager`.

----
package org.springframework.transaction;

import org.jspecify.annotations.Nullable;

public interface PlatformTransactionManager extends TransactionManager {

    // <.>
	TransactionStatus getTransaction(@Nullable TransactionDefinition definition) throws TransactionException;

    // <.>
	void commit(TransactionStatus status) throws TransactionException;

    // <.>
	void rollback(TransactionStatus status) throws TransactionException;
}

----

. create a transaction (and something to which we can ascribe subsequent work)
. commit the transaction and the batch of work therein
. or, if something's gone wrong, rollback the work

We can write code in terms of implementations - the `DataSourceTransactionManager` - of this interface and handle transactions in a consistent way across our code.
If we decide to work with Kafka tomorrow, we need only swap out the instance of the `PlatformTransactionManager` in a single place.

So, where to put this code?
Remember, we're using Java, a a good object-oriented language.
We've got to follow the single responsibility principle; each class should do one thing.
Transaction handling feels like a different concern.
I suppose we could extract it into another class that implements the same `DogRepository` interface, sets up and tears down the transactions, and then calls our actual target `DogRepository`.

Here's our new `TransactionalDogRepository`.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/tx1/TransactionalDogRepository.java[]
----

it's wrapped the core functionality, finding records, in a transaction.

In order for this arrangement to work we have to spin up a `PlatformTransactionManager` and rework our `Main` class.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/tx1/Main.java[]
----

<.> the instance given to the `test` method is still a `DogRepository` so it is none the wiser.

== Prefer Composition to Inheritance

This new wrapper class is a _composite_.
In object-oriented design there are two ways to introduce new features to a type system: specialization (subclassing) and composition.

Prefer composition to inheritance.
It buys you lots of _optionality_.
Optionality is wiggle room, freedom to make different decision later on with little cost or disadvantage later on. optionality is the bedrock of architecture: given constraints what choices should i make that most advantage me now and tomorrow?

* Flexibility at runtime.
Composition lets an object hold references to other objects and swap them out, so behavior can change dynamically.
Inheritance fixes the relationship at compile time.
* Avoids the fragile base class problem.
With inheritance, changes to a parent class can silently break subclasses that depended on its internals.
Composition isolates components behind their interfaces, so changes propagate less unpredictably.
* Escapes deep hierarchy rigidity.
Inheritance tends to grow tall, tangled class trees.
When you need behavior from multiple sources, single-inheritance languages force awkward workarounds; composition lets you assemble capabilities from independent pieces.
* Better encapsulation.
Subclasses often need to know how the parent works internally (protected members, method call order).
Composition only exposes the public interface of the parts you use, keeping coupling loose.
* Models "has-a" more honestly than forced "is-a".
Inheritance implies a true subtype relationship.
Developers frequently abuse it just to reuse code, creating relationships that aren't logically sound (a Stack is not really a List, even if it reuses one).
Composition expresses "uses" or "has" without that false claim.
* Easier testing.
Composed dependencies can be mocked or injected; inherited behavior is baked in and harder to isolate.

The tradeoff is a bit more boilerplate - you delegate calls to the contained objects rather than getting them "for free." Inheritance still fits genuine is-a relationships and when you want polymorphism through a shared base type.
The guidance is a default, not an absolute.

If you run `Main`, you'll see that we've got print outs and that we've started and stopped a transaction for every call.

// stop tx1
== Simplifed Transaction Management with `TransactionTemplate`
// start tx2
Im happy with what weve done but the result is certainly more verbose. imagine having to write all that boilerplate transaction code in a new composite method for every method we introuce in the original implementation. it wouldn't be so bad if we could do away with the fragile resource management and error handling logic.

The core arrangement is similar from one use to another. start transaction, do work. commit. or catch an exception and rollback. the only thing we really care about is the stuff in the middle - the work itself. another very interesting design pattern we care about is the _template_ pattern. here, we extract out that which changes from that which doesnt and hide that which doesnt change in a _template method_. its a template you see because you only need to fill out the parts that are unique to your situation.

Spring's `TransactionTemplate`, and `JdbcTemplate` - the precursor to Spring's `JdbcClient` - were gateway drugs for me.
I deleted thousands of lines of code when I first found these gems.

Let's refactor the `TransactionalDogRepository` to biuld on the `TransactionTemplate` instead.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/tx2/TransactionalDogRepository.java[]
----

_So_ much better!

Here's the refactored `Main` class, too.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/tx2/Main.java[]
----

<.> all we've done is introduce the `TransactionTemplate` which of course takes a pointer to the `PlatformTransactionManager`

// stop tx2
// start jdkproxy
== Cross-Cutting Concerns

The approach is conceptually clean enough but its obviously going to start becoming tedious as we add more methods, or more concerns.
Suppose wanted to add logging.
Or to add metrics.
Or to add security checks.
We'd have to wwrite more and more composites and for every new method in the core `DogRepository` interface, we'd have to add new methods in each of the composites.

what about ordering.
Which composite wraps which?
what if we wanted to support auditing, so for every write operation we want to also write an access log to a database. that would need to happen inside the transactional composite so that both the underlying write and the write to the audit table would be in the sane transaction.

this is where the object oriented approach starts to fall apart. weve got a common concern thatll be common to _all_ repositories. these are _cross-cutting_ concerns.

== Hold My Proxy!

the plan of attack for an object oriented language is to use composition or inheritance to introduce new concerns. but we cant scale that. wed get too many permutations of too many types in no time at all. so what if we could automatically do this? what if we could, at runtime, _programmatically_ create a class that implements the interface? java has a way to do this since java 1.4.

ive extracted out the really meta-programming magic into a separeate new class called `Transactions`.

Fair warning, this level of high wire metaprogrammming can be a little intense for folks not prepared for it. you dont need to retain all of it. lets just understand conceptually what's happening. were goinf to ask java to do two things at once: create a class that impleements the interface we want it to implement (`DogRepository`) and then create a single instance of that new class and return it back to us.

we provide a callback (here it's shown as a lambda; but it's actually an instance of the JDK's `InvocationHandler` type) that will be invoked whenever anybody invokes a method on the newly generated instance.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/jdkproxy/Transactions.java[]
----

<.> call `java.lang.reflect.Proxy.newProxyInstance(ClassLoader, Class[] interfaces, InvocationHandler)`
<.> in the `InvocationHandler` lambda, we're given a pointer to `this`, the instance that the `newProxyInstance` hands back to us.
We don't need it here.
<.> we're given a pointer to the `java.lang.reflect.Method` method that is being invoked. did the user call `toString` on the proxy instance? then this will be the `toString` method.
<.> we're given a pointer to the `Object[]` arguments that've been passed into the method when it was called.
In our case, we're going to be calling `findAll`, which takes no arguments, so this `Object[] args` will be empty.

Weird, isnt it?
But its a force multiplier that we need.
Itll allow us to acheive the same sort of runtime metaprogramming shenanigans youd expect with a duck typed language like JavaScript or Ruby, without giving up the type system for most of our code.

Let's rework our `Main` class, jettisoning the old, artisanal, hand-crafted  `TransactionalDogRepository` and instead using this new shortcut to simplify things.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/jdkproxy/Main.java[]
----

Again, from the perspective of our "test," nothing has changed. It expects a `DogRepository`, and a `DogRepository` it got.



//
// * still very tedious tho is there some way to programmatically generate new implementations of the interface?
// * jdk proxies
// * now we can wrap our target with our new `transactional` method


// stop jdkproxy
// start cglibproxy
* but what about concrete types w/ no interface?
* after all its an antipattern, to have an interface for just one type
* spring's proxyfactorybean
* we can delete the interface. huzzah
// stop cglibproxy
// start springframework
* its nice but things are getting out of hand. that said, our code is approachable enough for now.
* what if we wanted to do any kind of testing? wed have to duplicate all these beans
* and all of this just for a single query to a db! we havent even started to think about building a web application, messaging, observability, etc.
* lets see if spring can improve things
* turn everything into beans
* were wiring everything up with an `ApplicationContext`.
The AC is the thign that glues a `BeanFactory` into an application's environment.. it's _context_.
* the `BeanFactory` is the thing that does most of the work. its the thing that does depdnency injection.
* ingest -> BeanDefinitions -> beans
* u can inspect the BeanDefinitions with a `BeanFactoryPostProcessor`
* u must never call `getBean(Class<?>)`.
Use the beanName's and the method that gets the bean definitions.
// stop springframework
// start lifecycle
* there is a lifecycle at play. i can control the beans construction and destuction. they can implement InitializingBean && DisposablBean
* these callbacks are nbut one way to participate in important lifecycle events. another is to use `ApplicationEvent`s. there are a ton of them! lets implement a simple `@EventListener`
* the lifecycle is interesting. when the app starts up and shuts down ur code can hook into the lifecycle.
// stop lifecycle
// start pp
* let's look at `BeanFactoryPostProcessors` and `BeanPostProcessors`
* > ingest -> BeanDefintiions -> beans
* BeanFactoryPostProcessor lets u see the BeanDefintions
* we can demonstrate it. ive put it another configuration class. we can import configuration classes by adding `@Import` to the `DogConfiguration` configuration class.
* neat. what we want to do is introduce transactions however. so lets use a `BeanPostProcessor`.
* a BPP gets called right before the beans are put in service. we have a chance to enrich the object before its put into service.
* extract the transactional support to this based on presence of marker interface `Tx`
* nice! now we can refactor the config and remove the explicit call to `Transactions.createProxy`.
* _this_ is the power of a good framework. you can central cross-cutting concerns in a single place. this is the essence of aspect-oriented programming (AOP).
// stop pp
// start transactional
* if u have used spring at all before then u prolly know where this is going: we've already done this exact magic trick. let's refactor to use `@transactional`. just need to enable it with `@EnableTransactionManagment`
// stop transactional
// start componentscan
* nice but of course its tedious to define beans with full config every time. lets use implicit configuration and `@ComponentScan`
* component scanning for our repository by adding `@Repository`
* stereotype annotations are neat. u can create ur own, too
* this is _implicit_ configuration
* as opposed to the explicit configuration
// stop componentscan
// start beanRegistrar
* Spring Framework 7 introduced `BeanRegistrar`s, too, btw. here's how that would look.
* we turned almost all the beans into the BeanRegistrar format. we leave the DataSource in Java config and we still have component scanning for the DogRepository itself.
* you can mix and match. no need to pick one over the other. they all end up as BeanDefinitions that get turned into beans, and those beans can be injected and reused in all the normal ways.
// stop beanRegistrar
// start environment
* anyway weve done a lot here. but weve got harccoded configuration. let's extricate the values to properties (`application.properties`) and use the `Environment`
// stop environment
// start boot
* it's nice! but theres a lot of boilerplate thatll prolly be the same from one appt o another.
* lets use Spring Boot. same `ApplicationContext` but the code is much simpler.
We can delete everything except the DogRepository and the `test` method
* this works because of AutoConfiguration. you can create your own too. the autoconfig is activated by the presence of `starters`.
* and, being honest, im not sure we ever needed to implement the repository ourselves. lol. lets just use the Sprig Dats JDBC project.
* note that weve also now got good ascii art. we've got an actuator. weve got a web server.
* we can use virutal threads!
* also itll automatically initialize the schema of the DB for us (schema.sql and data.sql)
// start boot
* remember the BEanDefinitions? we can turn this into a graalvm native image!
* use spring boot's build plugin to create a docker image, too
