:code: ..

= From Beans to Boot

You know, I am assuming that by the time you're reading this that you have some background with Spring. I assumed the same thing about one of earlier books, _Reactive Spring_, too, but I included a _very_ simple discussion of some of the core principles of Spring in that book and - to my utter shock and chagrin - it was one of the most loved aspects of the book! I couldn't believe it!

So, here we go. We're going to do the same sort of thing, but of course greatly udpated to reflect the amazing moemnt in which we fnd ourselves.

when spring first came out we talked about the "spring triangle"  the three pillars that made the Spring Framework so useful for people:
 * portable service abstractions
 * dependency injection
 * autoconfiguration

more recently, with the introduction mof Spring Boot, we've added a new dimension of utility to the framework: autoconfiguration. So I guess its more like a "Spring square" now, come to think of it.

At the core of Spring as a framework is the fact htat it needs to understand how your objects are wired together. But why? why bother telling it these things? Why not just wire things yourself?

at the microlevel, this isnt an unreasonable quesiton. spring is just java and i can write java without spring, so why bother with Spring?

let's introduce a _trivial_ example to enforce the idea. Were going to read `Dog` data from a SQL database, PostgreSQl, running on our machine. Well use the follwoing Docker Compose file to stand up the instance of our database.

----
include::{code}/beans-to-boot/beans-to-boot/compose.yml[]
----
.run this in the usual way: `docker compose up -d`

// db start
* theres some SQL for schema and data in `schema.sql` and `data.sql`. run `docker compose up -d` then make sure to pass that SQL to postgresql:
```shell
PGPASSWORD=secret psql -Umyuser -hlocalhost mydatabase
```
// db stop
// raw start
* spring 'square' : psb, aop, di, autoconfig
* basic repository
* core java
* DataSource inline
// raw stop
// di start
* use DI to extract it out; nothing fancy just polymorphism.
// di start
// psb start
* use JdbcClient
// psb start
// tx1 start
* what about tx?
* oop says dry; extract single responsibility to another class
* TransactionalDogRepository is a composite that wraps the target one
* platformtxmanager
// stop tx1
// start tx1
* transactiontemplate
// stop tx1
// start jdkproxy
* still very tedious tho is there some way to programatically generate new implementations of the interface?
* jdk proxies
* now we can wrap our target with our new `transactional` method
// stop jdkproxy
// start cglibproxy
* but what about concrete types w/ no interface?
* after all its an antipattern, to have an interface for just one type
* spring's proxyfactorybean
* we can delete the interface. huzzah
// stop cglibproxy
// start springframework
* its nice but things are getting out of hand. that said, our code is approachable enough for now.
* what if we wanted to do any kind of testing? wed have to duplicate all these beans
* and all of this just for a single query to a db! we havent even started to think about building a web application, messaging, observability, etc.
* lets see if spring can improve things
* turn everything into beans
* were wiring everything up with an `ApplicationContext`. The AC is the thign that glues a `BeanFactory` into an application's environment.. it's _context_.
* the `BeanFactory` is the thing that does most of the work. its the thing that does depdnency injection.
* ingest -> BeanDefinitions -> beans
* u can inspect the BeanDefinitions with a `BeanFactoryPostProcessor`
* u must never call `getBean(Class<?>)`. Use the beanName's and the method that gets the bean definitions.
// stop springframework
// start lifecycle
* there is a lifecycle at play. i can control the beans construction and destuction. they can implement InitializingBean && DisposablBean
* these callbacks are nbut one way to participate in important lifecycle events. another is to use `ApplicationEvent`s. there are a ton of them! lets implement a simple `@EventListener`
* the lifecycle is interesting. when the app starts up and shuts down ur code can hook into the lifecycle.
// stop lifecycle
// start pp
* let's look at `BeanFactoryPostProcessors` and `BeanPostProcessors`
* > ingest -> BeanDefintiions -> beans
* BeanFactoryPostProcessor lets u see the BeanDefintions
* we can demonstrate it. ive put it another configuration class. we can import configuration classes by adding `@Import` to the `DogConfiguration` configuration class.
* neat. what we want to do is introduce transactions however. so lets use a `BeanPostProcessor`.
* a BPP gets called right before the beans are put in service. we have a chance to enrich the object before its put into service.
* extract the transactional support to this based on presence of marker interface `Tx`
* nice! now we can refactor the config and remove the explicit call to `Transactions.createProxy`.
* _this_ is the power of a good framework. you can central cross-cutting concerns in a single place. this is the essence of aspect-oriented programming (AOP).
// stop pp
// start transactional
* if u have used spring at all before then u prolly know where this is going: we've already done this exact magic trick. let's refactor to use `@transactional`. just need to enable it with `@EnableTransactionManagment`
// stop transactional
// start componentscan
* nice but of course its tedious to define beans with full config every time. lets use implicit configuration and `@ComponentScan`
* component scanning for our repository by adding `@Repository`
* stereotype annotations are neat. u can create ur own, too
* this is _implicit_ configuration
* as opposed to the explicit configuration
// stop componentscan
// start beanRegistrar
* Spring Framework 7 introduced `BeanRegistrar`s, too, btw. here's how that would look.
* we turned almost all the beans into the BeanRegistrar format. we leave the DataSource in Java config and we still have component scanning for the DogRepository itself.
* you can mix and match. no need to pick one over the other. they all end up as BeanDefinitions that get turned into beans, and those beans can be injected and reused in all the normal ways.
// stop beanRegistrar
// start environment
* anyway weve done a lot here. but weve got harccoded configuration. let's extricate the values to properties (`application.properties`) and use the `Environment`
// stop environment
// start boot
* it's nice! but theres a lot of boilerplate thatll prolly be the same from one appt o another.
* lets use Spring Boot. same `ApplicationContext` but the code is much simpler. We can delete everything except the DogRepository and the `test` method
* this works because of AutoConfiguration. you can create your own too. the autoconfig is activated by the presence of `starters`.
* and, being honest, im not sure we ever needed to implement the repository ourselves. lol. lets just use the Sprig Dats JDBC project.
* note that weve also now got good ascii art. we've got an actuator. weve got a web server.
* we can use virutal threads!
* also itll automatically initialize the schema of the DB for us (schema.sql and data.sql)
// start boot
* remember the BEanDefinitions? we can turn this into a graalvm native image!
* use spring boot's build plugin to create a docker image, too
