:code: ..

= Spring Boot
// start boot

We've come a long way, but done very, very little.
For all our troubles, we've only got one repository with one method.
Now imagine we were trying to build a real application.
We'd need security; we'd need to stand up a web server.
We'd need observability.
We'd need to package the application up for production.

Let's leverage Spring Boot.
It's already on the CLASSPATH.
Spring Boot builds on Spring Framework (and the rest of the Spring ecosystem).
It's just more Spring, taken a step further thanks to the power of something called _autoconfiguration_.
But first, let's refactor.

Here's the updated `Main` class.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/boot/Main.java[]
----

. Spring Boot's `@SpringBootApplication` annotation is itself a _meta-annotation_.
It is meta-annotated with `@Configuration`, which means this `Main` class is also a `@Configuration` class.
It's meta-annotated with `@ComponentScan`, so we don't need to worry about that either.
. because it's a `@Configuration` class, we can use `@Import` on it, just like before.
. through most of the code we've looked at, we've created a Spring `ApplicationContext`.
Here, we're doing the same thing.
The return value of `SpringApplication.run` is an `ApplicationContext`.
But we don't need it, because we don't need to explicitly look up the `DogRepository` to pass to our `test` method.
Instead...
. ...we can define a bean of type `ApplicationRunner`. `ApplicationRunner` beans are given a chance to run as close as possible to the moment when the application is fully initialized and right before it's put into service.
So, here, rather than squatting on the `main` method as we did in every earlier example, we simply register this bean.
We can register as many as we want, for whatever purpose, and know that this logic will run as the service initializes.


== Spring Data JDBC

We're using Spring Boot now.
We've got a full object-relational mapper (ORM) framework on the CLASSPATH.
Spring Data JDBC is capable, and it's already been configured.
Let's rework our repository to leverage it, rather than hand-rolling SQL ourselves.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/boot/DogRepository.java[]
----

I know, you're thinking: "Didn't we get rid of the interface ages ago?" But fear not!
The interface is back, but this is _way_ better: we got rid of the implementation!
This interface, which extends Spring Data's `ListCrudRepository`, already has a method called `findAll`.
It also has methods to `save`, `delete`, `findById`, etc.
Spring will create a proxy implementation of this interface at startup time and provide implementations for all those methods by default.
You can even define custom finder methods.
In this example, I've got a finder method called `findByName` that, when invoked, will execute a SQL query of the shape `select * from dog where name = ?`.
It does this by convention.
You can, of course, annotate the method in the interface with `@Query`, and Spring will use your query instead. _Much better!_

== Conventions over Configuration

Spring Boot has a ton of convenient conventions.
For example, it'll create a _real_ `DataSource` backed by the HikariCP connection pool, with properties loaded by convention from the Spring `Environment`.
Spring Boot will, by convention, load any `application.properties` or `application.yml` it finds in `src/main/resources`.

== AutoConfiguration

We imported the `DogBeanRegistrar`, so we might as well look at it.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/boot/Main.java[]
----

What happened?
Where are all our beans?!
They're gone.
(Almost) all gone.
Spring Boot provides those beans for us, thanks to its marvelous _autoconfiguration_.
So all that remains are our beans.

When Spring Boot starts up, it scans the CLASSPATH for any `.jar` containing a file called  `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`.
That file, in turn, contains a newline-delimited list of Java configuration classes' fully qualified names.
Functionally, these classes are the same as the other Java configuration classes we've seen so far, with some small refinements.
First, keep in mind that Spring Boot will _try_ to load every single one of these configuration classes on startup.
Sometimes the beans in these configuration classes are not important or useful in a particular situation.
It would be grossly inefficient if Spring Boot registered beans that we didn't need.
So, autoconfiguration classes and the `@Bean` methods within are guarded with `@Conditional` annotations.
These annotations point to implementations of the `Condition` type.
These `Condition` instances test something about the application or its environment, and if the test comes back positive, the beans are contributed to the `BeanFactory`.
If not, they are not contributed.

There are many such conditions.
Conditions to test for the presence or specific value of a property in the `Environment`.
Conditions to see whether you and I, the users, have or have not already defined beans of a particular type.
Conditions to see whether certain classes are present in the CLASSPATH.
These conditions let Spring Boot avoid defining beans that aren't needed, and degrade gracefully.
If we'd kept our `DriverManagerDataSource` from earlier, Spring Boot would've backed off on contributing its `DataSource`, because it would infer that we want to exert control here.
In this way, we get the best of both worlds: Spring Boot has sensible defaults that drop away whenever we want to override something.

We can (and should) create our own autoconfiguration if we want to leverage the same convention-over-configuration experience that Spring Boot promotes.

Create an autoconfiguration class of your own.
Be sure to put the code in a package that is _not_ scanned by Spring's component scanning mechanism.
In my application, my root package is `com.example.beans_to_boot`, so Spring will discover all classes in that package or deeper.
So, I'll put the autoconfiguration in a separate, adjacent, package called `com.example.autoconfigure`, not because it's required but because it confirms that we've wired up the autoconfiguration correctly.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/autoconfigure/SillyAutoConfigurationExample.java[]
----

. `@AutoConfiguration` is yet another meta-annotation.
You could use `@Configuration` here if you wanted.
. `@ConditionalOnRandomness` is a conditional annotation that we'll write ourselves in just a moment.
. `@ConditionalOnProperty` is a Spring Boot conditional annotation that will evaluate to true if the property called `my.config` exists in the `Environment`.
We further stipulate that the value will be matched if it's not specified.
If it is specified, and only if the value is `bar`, then this Java configuration bean will be registered.
If this test evaluates to true, you'll see the output of our `ApplicationRunner` when the application starts up.
If not, nothing will happen.

Let's look at the implementation of our (admittedly very contrived) condition.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/autoconfigure/ConditionalOnRandomness.java[]
----

. this annotation is a meta-annotation which we've annotated with Spring Framework's `@Conditional` annotation.
We pointed it to an implementation of `Condition` that we've written called..
. `RandomnessCondition`, which evaluates to true whenever the result of `Math.random()` is greater than `0.5`.

Obviously, this is a bit of a toy, but if you restart the program a few times you'll see your `ApplicationRunner` run and not run in seemingly random succession.

Now, create a text file in `src/main/resources/META-INF/spring/` called `org.springframework.boot.autoconfigure.AutoConfiguration.imports` in your project.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports[]
----

Here, we've got just the one class.
We could put this autoconfiguration class and the text file in a separate `.jar`, add that to the classpath of any Spring Boot application, and Spring Boot will give your code a chance to run _without_ requiring input from the user at all.
This is how you ship seamless, out-of-the-box, and productive developer experiences that scale.

== An Amazing Web Server

Spring Boot autoconfiguration does a whole heckuva lot more than register a `DataSource`.
You might notice that when you start the program, it doesn't just exit as soon as the `Dog` entities have been enumerated.
Spring Boot started a web server.
Why?
Because we asked it to by adding `Spring Web` to the project _way_ back at the very beginning of this chapter.
So we now have a full web framework and web server in play.

Here, I even wrote a trivial Spring MVC controller that loads all the results from the repository.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/boot/DogController.java[]
----

Run the program and then hit `http://localhost:8080/dogs` in your browser to see that it's working.

By the way, when you ran the program, did you notice the pretty colored log output?
And the _amazing_ ASCII art banner?

TIP: If you put a custom banner in `src/main/resources/banner.txt`, Spring Boot will use it instead of the default built-in ASCII art.

Remember when we first introduced `application.properties`?
I didn't speak to some of the configuration values in the property file.
Only those concerned with the `DataSource`.
Let's revisit some of those.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/resources/application.properties[]
----

. the original database credentials... moving on.
. this property enables virtual threads, a game-changing feature in Java 21 or later.
This will dramatically improve the scalability of blocking I/O.
. this property tells Spring Boot to run `src/main/resources/schema.sql` and `src/main/resources/data.sql` on startup.
Super convenient to ensure the system is correctly configured.

== Observable Services

Spring Boot is production-ready and worthy out of the box.
When you configured the application back on the Spring Initializr, you added the `Actuator` and `OpenTelemetry` dependencies.
The Actuator dependency brings in a slew of endpoints, usually mounted under `/actuator/*`.
There are many endpoints, but most of them are not visible unless you _expose_ them with another property added to `application.properties`.

If you want to see all the Actuator endpoints and the full health endpoint, you might use the following configuration properties.

----
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
----

Now you can visit `/actuator/metrics`, `/actuator/health`, `/actuator/beans`, `/actuator/configprops`, etc.
Visit just `/actuator` to see all the sub-endpoints.

We've also got Grafana running in the background.
As you work through the code in Spring Boot, you might notice that, first of all, you're seeing a good deal more application events.
Second, if you visit http://localhost:3000 and then navigate to `Drilldown` -> `Metrics`, you can see the same metrics you saw under `/actuator/metrics`.

== GraalVM Native Images

This application runs really quickly and scalably, but could it be faster and use less RAM?
Sure!
One way you might help with that is to embrace GraalVM native images. https://graalvm.org[GraalVM] is an OpenJDK distribution that carries with it some amazing extras.
You'll need to have it installed on your machine.
I'm using SDKMAN.io, so all I needed to do was:

----
sdk install java 25.0.2-graalce
sdk default java 25.0.2-graalce
----

I'm interested in the `native-image` compiler tool that comes with GraalVM.
It takes a Java program's `.class` files and turns them into native, operating-system- and architecture-specific machine code.
The kind you'd get from using C, Go, or Rust.
The result is a _markedly_ smaller memory footprint and a _markedly_ faster startup time, at the dubious expense of portability.
The resulting binaries only run on the platform for which they were compiled.
If you compile the binary in a Linux CI environment, it'll be fine in a Linux production environment, so it's not as big a deal-breaker as it might sound.

WARNING: Keep in mind that GraalVM native images are _not_ standard Java and in fact run counter in some ways to Java's write-once, run-anywhere mantra and promise of portability.

GraalVM was the first scenario where Spring Boot could leverage ahead-of-time code generation to transform the program into a form that would execute more efficiently at runtime.
One of the AOT transformations that's just been made possible in Spring Boot 4 and Spring Framework 7 is compile-time, ahead-of-time code generation for Spring Data repositories like our Spring Data JDBC repository.
For it to work, however, the AOT engine will need to know which SQL query dialect is being used _at compilation time_.

Add the following bean to help it along.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/boot/DataAotConfiguration.java[]
----

You can take advantage of native-image technology thusly:

----
./mvnw -DskipTests -Pnative native:compile
----

Then, stand back.
It might take a while.
Maybe even minutes.
On my machine, for this application, it takes about 30 seconds to do the full compile.
Your mileage may vary.

Try it.
Go to the `target` folder and run `target/beans-to-boot` or whatever your Maven artifact name was.

GraalVM can have _amazing_ results, but it does require some compromises about which you need to be aware. The way GraalVM works is by starting from your `main` method entry point into the application, scanning every class that you use, and every class that those classes use, and every class that those classes use, and so forth, and onward until its built up a giant graph of which classes your program will use. It retains those and throws every other class away before it compiles your program. It also throws away reflective metadata (you know, the types and instances that you get back when you try to do something like `Customer.class.getMethods()`). It also throws away the metadata for JNI references. And `Serialization`. Also, all the stuff that aren't `.class` files, but that ship in the `.jar` files for your application - things like `.properties` files, images, etc.? It throws all that away, too. Basically, all the stuff that the JVM normally would create and/or load on every startup, but that your program may never need: it throws it all away. The result is a _lightning_ fast native image which uses a tiny fraction of the usual RAM.

But it's not perfect. The analysis that results in this much smaller set of classes happens during compilation. Java's a turing complete language. It's impossible to completely understand at compile time what will happen at runtime. So the GraalVM compiler might throw things out that you might actually end up needing during runtime. So you'll need to tell it what to keep. What _not_ to throw out. Normally, in a GraalVM application, you do this with `.json` configuration files that live in `.jar` files under `/META-INF/native-image/$\{groupId}/$\{artifactId}/*.json`.

The trouble is that these configuration files are fiddly. If you refactor a type in your Java code, your IDE might forget to update the entry in the `.json` configuration file. So, you'll need to update it yourself. It gets tedious.

Spring Framework 6 and Spring Boot 3 introduced an Ahead of Time (AOT) component model that gets evaluated _during compilation_. Remember where we talked about the Spring `BeanFactory`, and said that the `BeanFactory` handles _ingest_ (the loading of bean configuration from various sources like component scanning, Java configuration, etc), then turned everything into metamodel objects of the class  `BeanDefinition`? Those `BeanDefinition` objects give any would be examiner enough information about the objects in the application, including their classes.

Spring's AOT component model builds your application, to that point, giving you access to the `BeanDefinition` objects, and allowing you to programmatically register _hints_, which get translated into the aforementioned `.json` files.

We won't belabor the point, but there are different ways to register these AOT hints, depending on the level of power you need.

For most applications, users should probably get comfortable with `RuntimeHintsRegistrar`.

Let's suppose we wanted to read in a text file (`message`) and write out its contents to the command line when the program starts up. You could easily construct a `Resource` object and then read its contents in the JVM. But that text file won't exist in a GraalVM native image, because it'll have been thrown out. We need to tell GraalVM not to.

Here's the text file.
----
include::{code}/beans-to-boot/beans-to-boot/src/main/resources/message[]
----

Now we need to register some code to contribute the AOT hints.

----
include::{code}/beans-to-boot/beans-to-boot/src/main/java/com/example/beans_to_boot/boot/AotConfiguration.java[]
----
. The `AotConfiguration` class is a stock-standard Java configuration class. The `@ImportRuntimeHints` annotation loads the AOT `RuntimeHintsRegistrar` class. This class will be invoked during compilation.
. Spring's `Resource` abstraction is a nice way to represent anything that could be read (that is, it produces `byte`) or written to. There are many implementations. Here we're using the one to represent resources on the CLASSPATH.
. the `RuntimeHints` object offers convenient DSL methods to register resources for loading, types for reflection, or serialization, etc.
. By the time this `ApplicationRunner` executes at runtime, the `message` file _will_ be in the memory of the native image and everything will continue to work, all because of the work we did at compile time to make it so.

Conceptually, that's all there is to it! There are other callback classes besides `RuntimeHintsRegistrar`, but that's a topic for discussion some other day. What's important to know is that you'll almost never need to worry about registering these AOT hints. Spring Boot will do it. Or there'll be configuration in the libraries that you consume. But not _always_. In which case, you'll have to do the work yourself. But at least you now know how.


== Project Leyden

GraalVM native images are my favorite approach for optimization, but they do come with their own caveats.
They don't always work without finessing, and I won't get into all that here, but there is a whole Spring Ahead-of-Time (AOT) component model that allows you to add supplementary configuration to your Spring Boot applications so that they behave well in a GraalVM native-image context.

If you want a standard way to improve the startup time (and not much else) of your application, you can also use Project Leyden, part of the core Java SDK.
It works reliably on _every_ program, with no compromises, but the results aren't quite as impressive, either.

The thrust of it is that you run the program in a special mode: the JVM dumps out information about which things are used into a file, and that file can then be fed into the `java` CLI on a subsequent run so it'll start up a lot faster.
On my machine, this application is almost 50% faster on startup as a result of using Project Leyden.
Here's an example of doing this training run and then getting great results.

----
include::{code}/beans-to-boot/beans-to-boot/leyden.sh[]
----

. clean up and staging
. use Spring's AOT mode and do a package
. move the resulting packaged `.jar` to a well-known name, `application.jar`
. run the program using Spring Boot's `.jar` tools to extract the normally nested Spring Boot `.jar` into a folder called `autoconfigure`.
. run the Java program up until the application context's been refreshed, and dump the analysis out to `app.aot`.
. cleanup
. finally, run the program but use the `app.aot` index to dramatically speed up the application.

== The Spring Boot Buildpack integration

For most scheduling solutions, you'll need a container containing your application.
This doesn't mean that you'll need a `Dockerfile`, however.
Quite the contrary.
You're better off automatically building the container rather than manually defining it.
In the world of mystery meat cloud containers, _less is more_.

Spring Boot's Maven and Gradle plugins can do the work for you by deferring to the https://buildpacks.io[Buildpacks project].
Buildpacks provide recipes for taking application artifacts and packaging them up as containers.
These recipes represent the collective wisdom of the Spring and Java communities that maintain them.
There are also buildpacks for scores of other languages and ecosystems, including COBOL!

Here's how you can use it for your own application.
If you want to build a container for a standard JVM-based application, do the following.

----
./mvnw -DskipTests spring-boot:build-image
----

If you want to build a container for a GraalVM native image, do the following:

----
./mvnw -DskipTests -Pnative spring-boot:build-image
----

Let this run for a bit, and it'll give you the name of the container that's just been created.
You can run it or `docker push` it to whatever container registry you want.
From there, you're off to production!

== Next Steps

In this section we explored the awesome force-multiplying potential of Spring Boot and saw how it frees you to focus on that which matters, building the best and most valuable application for your customers as possible.

